### ISSUE TITLE
Revise the documentation of kubernetes deployment

### ISSUE THREAD

**Issue by sighingnow** [v6d-io/v6d#1031]
Describe your problem
---------------------

Please revisit the documentation (`k8s/README.md`, as well as `docs/notes/deployment/kuberentes` to cover newly added things in recent PRs about the component, deployment, usage, as well as internal design/implementation.

Additional context
------------------

**Comment by sighingnow** [comment]
If possbile, adding examples for newly added features, to help users getting started with vineyard on Kubernetes.

**Comment by dashanji** [comment]
Make sense, I will add a new pluggable driver `repartition` and reflect the code later, and add a detailed doc about all usage of the vineyard operator finally.

**Comment by sighingnow** [comment]
Closed by https://github.com/v6d-io/v6d/pull/1051
