### ISSUE TITLE
Optimize the deployment of vineyard operator in helm chart

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1059]
Describe your problem
---------------------

Add some options in `values.yaml` and improve the relevant doc.

**Comment by sighingnow** [comment]
Close as the webhook can be optionally disabled and please open new issues if we need further specific optimization on the helm charts.

**Comment by sighingnow** [comment]
Reopen as the enable webhook option has been removed from https://github.com/v6d-io/v6d/pull/1065, and we may be need to figure out how to proceed in other ways in the future.

**Comment by dashanji** [comment]
Yeah, a possible way is to add a flag to `helmify` for generating those webhook judgments, and I have opened an [issue](https://github.com/arttor/helmify/issues/57) there.

**Comment by sighingnow** [comment]
Should be resolved after some refactor for the webhook part, e.g., #1341.
