### ISSUE TITLE
missing `v6d-0.12.0.tar.gz` for 0.12.0 release

### ISSUE THREAD

**Issue by chenrui333** [v6d-io/v6d#1091]
It looks like 0.12.0 release does not have `v6d-0.12.0.tar.gz` and `v6d-0.12.0.zip`, just raise some awareness, thanks!

**Comment by sighingnow** [comment]
Hi @chenrui333,

Thanks for raising it up! Do you mean v6d-0.11.1? We haven't release v0.12 yet.

Now the source tarball has been upgraded, see: https://github.com/v6d-io/v6d/releases/tag/v0.11.1

Thanks!

**Comment by sighingnow** [comment]
Closing as resolved.

**Comment by chenrui333** [comment]
Yeah, I think it is 0.11.1 I was referring to, not quite sure why I typed 0.12.0 😮‍💨

**Comment by chenrui333** [comment]
Thanks for the quick fix!

**Comment by chenrui333** [comment]
Hi @sighingnow, looks like now the release is official, but I can still not see `v6d-0.11.2.tar.gz`? Thanks!

**Comment by sighingnow** [comment]
Fixed after rerun the CI workflows.

Thanks for letting me know that!
