### ISSUE TITLE
v6d 0.11.3 regression build failure

### ISSUE THREAD

**Issue by chenrui333** [v6d-io/v6d#1122]
Describe your problem
---------------------

When regression build v6d 0.11.3, we found an build failure against boost 1.81.0 (I dont think it is boost related).

The error is as below
```
[1m/tmp/vineyard-20230101-30335-9s7bcl/v6d-0.11.3/modules/graph/utils/table_shuffler.cc:187:9: [0m[0;1;31merror: [0m[1minvalid operands to binary expression ('grape::InArchive' and 'std::string_view' (aka 'basic_string_view<char>'))[0m
   arc << ptr->GetView(x);
[0;1;32m    ~~~ ^  ~~~~~~~~~~~~~~~

[0m[1m/tmp/vineyard-20230101-30335-9s7bcl/v6d-0.11.3/modules/graph/utils/table_shuffler.cc:226:9: [0m[0;1;31merror: [0m[1minvalid operands to binary expression ('grape::OutArchive' and 'vineyard::arrow_string_view' (aka 'basic_string_view<char>'))[0m
   arc >> val;
[0;1;32m    ~~~ ^  ~~~
```

----------------------------------------------------------------------

If is is a **bug report**, to help us reproducing this bug, please provide information below:

1. Your Operation System version (`uname -a`): macos/darwin
2. The version of vineyard you use (`vineyard.__version__`): 0.11.3
3. Versions of crucial packages, such as gcc, numpy, pandas, etc.: 
```
CPU: quad-core 64-bit dunno
Clang: 14.0.0 build 1400
Git: 2.37.1 => /usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: 14.1.0.0.1.1665256668
Xcode: 14.1
Rosetta 2: false
```
4. Full stack of the error (if there are a crash): See above
5. Minimized code to reproduce the error: I think CI should catch this, I will regression test with the master branch later

Additional context
------------------

relates to https://github.com/Homebrew/homebrew-core/pull/119529
full build log in here, https://pipelines.actions.githubusercontent.com/serviceHosts/d065b819-d194-4baa-bc84-7b4a294d8693/_apis/pipelines/1/runs/546333/signedlogcontent/22?urlExpires=2023-01-01T17%3A03%3A49.2347800Z&urlSigningMethod=HMACV1&urlSignature=8ToE6AjLW725vLnjqhEtzo1s20wS1rm8himWoVdnlS0%3D (sorry, the github action log is not quite readable)

**Comment by sighingnow** [comment]
I would try to cut a new release to see if the problem exists on latest vineyard.

**Comment by sighingnow** [comment]
I think the failure might be related to a recent upgrade of libgrape-lite: https://github.com/v6d-io/v6d/issues/1122

**Comment by sighingnow** [comment]
Hi @chenrui333,

I have created a bump-up pull request on homebrew repo: https://github.com/Homebrew/homebrew-core/pull/119581

FYI.

**Comment by chenrui333** [comment]
Thank you! I am good now. 🍻
