### ISSUE TITLE
[Bug] Compile vineyard got `InArchive <<(const std::string_view) not found` error with apache arrow 10.0

### ISSUE THREAD

**Issue by acezen** [v6d-io/v6d#1133]
Describe your problem
---------------------
Apache arrow 10.0 `GetView` method in `StringArray` return [`std::string_view` ](https://arrow.apache.org/docs/cpp/api/array.html#_CPPv4NK5arrow15BaseBinaryArray7GetViewE7int64_t)

When compile vineyard with arrow 10.0, it would report error:
```bash
/Users/weibin/Dev/v6d/modules/graph/utils/table_shuffler.cc:187:9: error: invalid operands to binary expression ('grape::InArchive' and 'std::string_view' (aka 'basic_string_view<char>'))
    arc << ptr->GetView(x);
```

----------------------------------------------------------------------

If is is a **bug report**, to help us reproducing this bug, please provide information below:

1. Your Operation System version (`uname -a`): MacOs
2. The version of vineyard you use (`vineyard.__version__`): latest
3. Versions of crucial packages, such as gcc, numpy, pandas, etc.:
4. Full stack of the error (if there are a crash):
6. Minimized code to reproduce the error:

----------------------------------------------------------------------

If it is a **feature request**, please provides a clear and concise description of what you want to happen:

### The behaviour that you expect to work:

Additional context
------------------

**Comment by sighingnow** [comment]
Could you please try upgrade your libgrape-lite installation to latest version (master)?

**Comment by acezen** [comment]
> Could you please try upgrade your libgrape-lite installation to latest version (master)?
Fixed by upgrade libgrape-lite to latest version.
