### ISSUE TITLE
Implement a vineyard management command-line to manage all vineyard components

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1152]
Describe your problem
---------------------

To make it easier for users to manage vineyard components in various environments, we propose the `vineyardctl`, which is a command-line component management tool that can help to manage the vineyard cluster on the different environments(local system、docker、kubernetes).

**GOAL**
- Managing vineyard components(vineyard server、vineyard client、vineyard operator)
- Deployment(local ststem 、docker、kubernetes).
- Version Update.
- Monitor(status monitoring、Log collection and alarming).
- Vineyard operator operations(assembly、repartition、sidecar、schedule, etc)
- Vineyard client operations(migration、get、put, etc)

**Non-GOAL**
- Not for downloading the vineyard components.

**Related issues**
https://github.com/v6d-io/v6d/issues/1088

Now the issue is in RFC status, please feel free to give your constructive advice. @sighingnow @septicmk @siyuan0322 

BTW, The feature may need a long time to realize.

**Comment by sighingnow** [comment]
Merged into vineyard in https://github.com/v6d-io/v6d/pull/1217, closing.
