### ISSUE TITLE
The vineyard operator documentation site failed to load the architecture graph. 

### ISSUE THREAD

**Issue by liusitan** [v6d-io/v6d#1162]
<img width="911" alt="image" src="https://user-images.githubusercontent.com/20542539/214141869-199a1f53-2eba-4336-a0e2-5f4109958cda.png">

**Comment by dashanji** [comment]
Thanks for the contribution in the Spring Festival, we'll deal with it after the vacation.

**Comment by liusitan** [comment]
you are welcome look forward to your update
________________________________

**Comment by sighingnow** [comment]
Hi @liusitan,

Thanks for reporting! The vineyard docs is under heavy refactor and the latest version of docs can be found from the [dev/docs](https://github.com/v6d-io/v6d/tree/dev/docs) branch.

The new docs website would be delivered before the end of this month.

**Comment by liusitan** [comment]
thanks, looking forward to it!

Best,
Sitan Liu


________________________________

**Comment by sighingnow** [comment]
Closed as #1253 merged. The new vineyard operator docs is placed at https://v6d.io/notes/cloud-native/vineyard-operator.html.
