### ISSUE TITLE
stream feature request

### ISSUE THREAD

**Issue by wuyueandrew** [v6d-io/v6d#1171]
If it is a **feature request**, please provides a clear and concise description of what you want to happen:

### What is the problem:

1. Stream with single writer and single reader, operation of reading is not repeatable.

### The behaviour that you expect to work:

1. As a kind of immutable data, stream can support single writer multiple reader. current_reading_ is not essential.
Maybe add a index param to client PullNextStreamChunk is better, it can support single writer multiple reader.
An alternative solution is add an StreamReset function, it's more compatible but reading is serial.

Additional context
------------------

**Comment by sighingnow** [comment]
Thanks for proposing!

> single writer multiple reader.

Do you expect multiple readers receive the same content, or, each receive some of those chunks?

**Comment by wuyueandrew** [comment]
> Thanks for proposing!
> 
> > single writer multiple reader.
> 
> Do you expect multiple readers receive the same content, or, each receive some of those chunks?

I wish 'multiple readers receive the same content'.
if one reader stop by some reason, another reader can retry from the start chunk. 
Or a stream is required by more than one program.
Anyway, read immutable data is threadsafe, its no need to limit one reader.

> Maybe add a index param to client PullNextStreamChunk is better, it can support single writer multiple reader.
this way can support both multiple readers receive the same content and receive some of those chunks, it's up to user.

**Comment by sighingnow** [comment]
Stream is designed for cases where we don't want to keep whole memory while processing chunk by chunk. There's some confilict that, if multiple readers are expected to receive the same content, then it would be hard to tell when to release memory.

A possible solution is adding something like `set_consumer_num` before opening the first reader, or, something like `Collection` rather than `Stream` is a proper solution for such cases.

**Comment by wuyueandrew** [comment]
You mean the reader should release memory, that's why 'single writer and single reader' for now, a reader dont know when other readers finish their reading?
If yes, it's hard to  release memory when reader crash.

**Comment by sighingnow** [comment]
> a reader dont know when other readers finish their reading?

Yes.

But I agree that the situation can and should be improved by:

- introduce something like `set_consumer_num` to allow multiple readers and release the memory once the last one finished
- introduce an enum `Repeated/Partitioned` to support both consumption mode
- introduce a `Collection` class for non-releasable consumption (WIP).

**Comment by wuyueandrew** [comment]
`set_consumer_num`  AND  `Repeated/Partitioned` are enough to support the cases we discussed early.
`introduce a Collection class for non-releasable consumption (WIP).` I dont understand , is it mean stream are released by
vineyard server when the stream is drained.
one last question, the release of stream should be executed by who in current version ? And who in improved version ?

**Comment by sighingnow** [comment]
- In current version, by vineyardd: vineyardd will release the current chunk when the reader moving to the next chunk by `PullNextStreamChunk`
- in futuer version, by vineyardd as well: vineyard will release the current chunk when it knows that the chunk has been consumed for `set_consumer_num` times.

**Comment by sighingnow** [comment]
We have recently introduced the `Collection<T>` APIs in #1197. We would like back to there it there are further actual need for multiple-producer/multiple-consumer streams.
