### ISSUE TITLE
Less boring warning messages from the k8s/Makefile

### ISSUE THREAD

**Issue by sighingnow** [v6d-io/v6d#1240]
Describe your problem
---------------------

It should not be a bug, but could you do something like `xxx 2>/dev/null` to ignore those boring warning messages?

![image](https://user-images.githubusercontent.com/7144772/223606026-a201b3e0-d37f-414a-af98-64ee6052a79d.png)

Additional context
------------------

**Comment by dashanji** [comment]
Ok.
