### ISSUE TITLE
Reduce/optimize the binary size of current vineyardctl

### ISSUE THREAD

**Issue by sighingnow** [v6d-io/v6d#1268]
Describe your problem
---------------------

Current vineyardctl is about 100M before strip and 70M even after strip, that is not very friendly to distribute the binary.

Not at high priority, and should be done after we finish the refactor of vineyardctl. The optimization could be done by analyze the dependency graph and prune not needed ones.

Additional context
------------------

- [vineyardctl](https://github.com/v6d-io/v6d/tree/main/k8s/cmd)
- [vineyard operator doc](https://v6d.io/notes/cloud-native/vineyard-operator.html)

**Comment by PTTQ** [comment]
你好，我想申请这个项目。

**Comment by dashanji** [comment]
Hi @PTTQ, thanks for your interest in the project. To be clear, whether the application for the project can be successful mainly depends on the quality of the proposal submitted in the end. Therefore, I highly recommend you first familiarize yourself with the project. Of course, if you encounter any problems during this process, you can report them here, and we will try to help you.

**Comment by sighingnow** [comment]
@zhuyi1159 @dashanji Try using https://github.com/Zxilly/go-size-view to analyze our dependencies to see if we can do something to make the vineyardctl binary size smaller (and simpler).

**Comment by zhuyi1159** [comment]
OK.

**Comment by zhuyi1159** [comment]
<img width="1734" alt="image" src="https://github.com/v6d-io/v6d/assets/57618314/b4993254-7976-4ad7-bba4-a300dbb82593">
It seems that dependencies only make up a small part of the binary file, but I have no idea how to handle the parts outside of the dependencies

**Comment by sighingnow** [comment]
May be you need to build a debug version to keep all those symbols? 

The major part is "C" and looks quite strange.

**Comment by zhuyi1159** [comment]
I use the following command: go build -gcflags=all="-N -l" main.go
In theory, all symbolic information should be preserved. Could you be more specific? I'm not sure "build a debug version" means for what.

**Comment by sighingnow** [comment]
Maybe `go build -gcflags=all="-N -l"` would be helpful?

**Comment by dashanji** [comment]
I think using the tool https://github.com/knz/go-binsize-viz is more meaningful.

![image](https://github.com/v6d-io/v6d/assets/71587243/e1f00df1-4977-4bb6-ae84-46c9a775bdc4)

**Comment by dashanji** [comment]
Also, we can find similar tools as well. It's only to show the package occupancy rate. Actually, we need to explore the code and reduce the dependencies.

**Comment by sighingnow** [comment]
> Actually, we need to explore the code and reduce the dependencies.

Agree.

**Comment by dashanji** [comment]
@zhuyi1159, I highly recommend starting something simple as follows.
- Check the code carefully and clean the unused code.
- Reuse the same logic package and reduce duplications. (refer to `go.mod`)

**Comment by dashanji** [comment]
Running the following command to get the dependency size.
```bash
$ cd k8s && go build -a -v cmd/main.go 2>&1 | grep -v vendor > built.txt
$ cat built.txt | xargs -L 1 -I {} go build -o "{}.a" {} find . -type f -name "*.a" -exec du -h {} \;  | sort -h | tail -n 20
```

```bash
3.7M    ./golang.org/x/net/http2.a
3.7M    ./k8s.io/api/apps/v1beta2.a
3.8M    ./k8s.io/apiserver/pkg/server.a
3.9M    ./k8s.io/apiserver/pkg/server/options.a
4.1M    ./github.com/v6d-io/v6d/k8s/controllers/k8s.a
4.3M    ./k8s.io/kubernetes/pkg/apis/core/validation.a
4.6M    ./github.com/gogo/protobuf/proto.a
5.0M    ./google.golang.org/protobuf/internal/impl.a
5.2M    ./k8s.io/kubernetes/pkg/apis/core.a
5.4M    ./k8s.io/apimachinery/pkg/apis/meta/v1.a
5.5M    ./k8s.io/kubernetes/pkg/apis/core/v1.a
5.6M    ./github.com/google/gnostic/openapiv2.a
5.6M    ./github.com/google/gnostic/openapiv3.a
5.7M    ./k8s.io/api/extensions/v1beta1.a
5.8M    ./k8s.io/client-go/applyconfigurations/core/v1.a
6.9M    ./net/http.a
8.2M    ./go.etcd.io/etcd/api/v3/etcdserverpb.a
8.5M    ./runtime.a
15M     ./github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.a
21M     ./k8s.io/api/core/v1.a
```

**Comment by sighingnow** [comment]
Closing as there are no further steps to reduce the binary size.
