### ISSUE TITLE
Deploying vineyard cluster via `vineyardctl deploy vineyard-cluster` occasionally fail in ci

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1284]
Describe your problem
---------------------

While testing `vineyardctl deploy vineyard-cluster` in the ci, it occasionally appears that the webhook is not ready, resulting in the [vineyardd can't be created](https://github.com/v6d-io/v6d/actions/runs/4575204301/jobs/8109431019#step:25:1404).  But if we deploy the vineyard cluster in the local machine, the command always works fine.

**Comment by sighingnow** [comment]
> 

Will increasing timeout or retry limit help?

**Comment by dashanji** [comment]
> limit

I have increased the timeout of the webhook but it doesn't work. Also, I can't find the retry count of the webhook configuration. The current webhook checker only checks the network address but not the route address of the webhook.
So I can't find a good solution to address it unless the upstream can support checking the webhook ready of a specific CRD.
https://github.com/v6d-io/v6d/blob/50e251fcfd98e0b4409ccbb32ec20f5c3aa4f6a4/k8s/cmd/commands/manager/manager.go#L217-L222

A common way to check whether the webhook is ready is to create a dummy vineyardd, but I think this will confuse the users as lots of resources will be created and deleted.

**Comment by sighingnow** [comment]
Can we define our own checker as the predefined one, but with a longer timeout (and retry if needed)?

(Hints: our own retry could takes the `s *Server` as argument).

```
// StartedChecker returns an healthz.Checker which is healthy after the
// server has been started.
func (s *Server) StartedChecker() healthz.Checker {
	config := &tls.Config{
		InsecureSkipVerify: true, // nolint:gosec // config is used to connect to our own webhook port.
	}
	fmt.Println("startedchecker")
	return func(req *http.Request) error {
		s.mu.Lock()
		defer s.mu.Unlock()
		fmt.Println("step1here")
		if !s.started {
			return fmt.Errorf("webhook server has not been started yet")
		}

		d := &net.Dialer{Timeout: 10 * time.Second}
		conn, err := tls.DialWithDialer(d, "tcp", net.JoinHostPort(s.Host, strconv.Itoa(s.Port)), config)
		fmt.Println("myweb is: ", net.JoinHostPort(s.Host, strconv.Itoa(s.Port)))
		if err != nil {
			return fmt.Errorf("webhook server is not reachable: %w", err)
		}

		if err := conn.Close(); err != nil {
			return fmt.Errorf("webhook server is not reachable: closing connection: %w", err)
		}

		return nil
	}
}
```

**Comment by dashanji** [comment]
> 

Good idea, I'll try it later.
