### ISSUE TITLE
building error which missing string_view 

### ISSUE THREAD

**Issue by wuyueandrew** [v6d-io/v6d#1288]
Describe your problem
---------------------

building vineyard graph -> cannot find libgrape-lite -> building libgrape-lite (contains string_view)
vineyard graph also require string_view and it cannot be found

![image](https://user-images.githubusercontent.com/28866983/230343362-f97778a0-add9-40eb-9908-d3e2df3ebd05.png)

----------------------------------------------------------------------

**Comment by dashanji** [comment]
Hi @wuyueandrew, I have checked the installation of the latest vineyard, but don't encounter the error you reported. Could you please try the latest version again refer to the [doc](https://v6d.io/notes/developers/build-from-source.html#install-from-source). If you encounter any errors after that, please feel free to let us know, and we'll handle them as soon as possible.

**Comment by wuyueandrew** [comment]
> Hi @wuyueandrew, I have checked the installation of the latest vineyard, but don't encounter the error you reported. Could you please try the latest version again refer to the [doc](https://v6d.io/notes/developers/build-from-source.html#install-from-source). If you encounter any errors after that, please feel free to let us know, and we'll handle them as soon as possible.

i built v6d  base on docker image ubuntu:latest, maybe ur env already install string_view.
shall i paste my dockerfile here ?

**Comment by sighingnow** [comment]
The patch #1289 has been merged. It was indeed a bug. Thanks for fixing.

**Comment by wuyueandrew** [comment]
thanks
