### ISSUE TITLE
In worker process, .put results in CreateBuffer: the fd is not matched between client and server

### ISSUE THREAD

**Issue by JustasB** [v6d-io/v6d#1324]
Describe your problem
---------------------

BUG

I receive the following error when attempting to `.put` a numpy array in a worker process:

```CreateBuffer: the fd is not matched between client and server```

----------------------------------------------------------------------

If is is a **bug report**, to help us reproducing this bug, please provide information below:

1. Your Operation System version (`uname -a`): Linux 194670edab96 5.13.0-48-generic #54~20.04.1-Ubuntu SMP Thu Jun 2 23:37:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
2. The version of vineyard you use (`vineyard.__version__`): '0.14.0'
3. Versions of crucial packages, such as gcc, numpy, pandas, etc.: numpy.__version__: '1.23.5'
4. Full stack of the error (if there are a crash):

```
Traceback (most recent call last):
  File "/src/./apps/web/views.py", line 51, in get
    result = InferencePipeline().predict_one(arguments)
  File "/src/inference_pipeline.py", line 83, in predict_one
    output = Queue().enqueue_and_wait(
  File "/src/./apps/web/queue.py", line 78, in enqueue_and_wait
    raise Exception(result['error'])
Exception: Traceback (most recent call last):
  File "apps/web/queue.py", line 98, in work_one_task
    result['result'] = getattr(import_string(class_name)(), method)(args)
  File "/src/inference_model.py", line 60, in predict_one_from_input_file
    print(sh.get(sh.put(numpy.zeros((3, 3)))))
  File "/opt/conda/lib/python3.8/site-packages/vineyard/core/builder.py", line 174, in put
    meta = get_current_builders().run(client, value, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vineyard/core/builder.py", line 87, in run
    return self.__factory[ty](client, value, **kw)
  File "/opt/conda/lib/python3.8/site-packages/vineyard/data/tensor.py", line 65, in numpy_ndarray_builder
    meta.add_member('buffer_', build_numpy_buffer(client, value))
  File "/opt/conda/lib/python3.8/site-packages/vineyard/data/utils.py", line 138, in build_numpy_buffer
    return build_buffer(client, address, array.nbytes)
  File "/opt/conda/lib/python3.8/site-packages/vineyard/data/utils.py", line 128, in build_buffer
    buffer = client.create_blob(size)
vineyard._C.InvalidException: Invalid: {"error":"CreateBuffer: the fd is not matched between client and server","fd_recv":15,"fd_sent":-1,"response":{"created":{"data_offset":5292288,"data_size":72,"is_gpu":false,"is_owner":true,"is_sealed":false,"map_size":268435464,"object_id":9242885988115704108,"pointer":139821645865216,"store_fd":15},"fd":-1,"id":9242885988115704108,"type":"create_buffer_reply"}}
```

6. Minimized code to reproduce the error:

In main web process, the following works without errors:
```
            sh = vineyard.connect('/tmp/vineyard.sock')
            print(sh.get(sh.put(1)))
            print(sh.get(sh.put(numpy.zeros((3, 3)))))
```

However, in a queue worker process, the last line fails with the above error:
```
            sh = vineyard.connect('/tmp/vineyard.sock')
            print(sh.get(sh.put(1))) # <-- OK
            print(sh.get(sh.put(numpy.zeros((3, 3)))))  # <-- CreateBuffer: the fd is not matched between client and server
```

Additional context
------------------

It's probably unlikely that the error can be reproduced, so I'm mostly looking for clues as to what the error message might mean and any additional steps I could take to debug the underlying cause.

**Comment by JustasB** [comment]
Hi @sighingnow, 

That's correct, both the main process (where the statement works) and the queue worker process (where the last statement always results in the error) are running inside a docker container.

**Comment by sighingnow** [comment]
> Upon closer inspection, this is happening on a .put, not a .get (as can be seen in the stacktrace). I'll update the OP and title.

Is this issue stably occurs/stably reproducible? Or just encountered it just once?

**Comment by sighingnow** [comment]
Hi @JustasB,

I would like you to know that we have made some progress to mitigate the issue and have uploaded a new release (v0.14.1) to pypi.

You could try upgrade your vineyard installation in your docker by

```bash
pip3 install -U vineyard==0.14.1
```

Fell free to tell us more if you still encounter this error. Thanks!

**Comment by sighingnow** [comment]
Closing as resolved. @JustasB  Feel free to reopen if you still encounter this issue.

Thanks!
