### ISSUE TITLE
Can v6d support graph data's incremental update?

### ISSUE THREAD

**Issue by songqing** [v6d-io/v6d#1344]
Describe your problem
---------------------

Now, v6d seems only support graph data's full update, in other words, loading the graph data once and then serving. It also supports adding new labels, but for the existed label, it seems the data can not be changed.
Loading the full data every time may be time-costed. If we have a full dataset and other small incremental dataset, supporting incremental update may be more efficient.

----------------------------------------------------------------------

If it is a **feature request**, please provides a clear and concise description of what you want to happen:

### What is the problem:
v6d's data incremental update for graph

### The behaviour that you expect to work:
We can load the full data at first, and then load some small  incremental updated data for the existed label.

**Comment by sighingnow** [comment]
Thanks for posting. We are planning to support graph's data incremental update in two folds:

- Add bulk data to existing vertex/edge labels

  Tracked by #1295 and is hopefully finished by the end of this August.

- Continuously adding vertices/edges in a streaming fashion to the existing graph

   We are working on a project called GART which maintains a mutable graph on top of vineyard with snapshot isolation and supports feeding streaming graph updates, which will be open-sourced soon. Stay tuned!

**Comment by sighingnow** [comment]
I'm going to move this thread to discussion.
