### ISSUE TITLE
Build a test demo of kubernetes cluster for vineyardctl unit test

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1418]
Describe your problem
---------------------

We'd better provide a test infra of kubernetes cluster to simplify writing the unit test case.

Related to #1396

**Comment by sighingnow** [comment]
When kind/minikube is not enough?

**Comment by dashanji** [comment]
Sorry, I may not express this clearly. For the unit test, we only need to check the function work as expected, and the test time should be as quick as possible. It's not suitable to build a kubernetes cluster with kind/minikube every time we run the unit test.

The issue is to introduce the [Envtest](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest) to build a simple control plane(etcd and kube-apiserver), and some tools like (monkey)[https://github.com/bouk/monkey] to replace some functions during the unit test as the kubernetes resources don't have a status on the control plane. 

The above may bring a lot of burden to newbies, so I think it's better to prepare the prerequisites and show a demo so that they can focus on how to write the test cases rather than the test infra.

**Comment by dashanji** [comment]
After discussion, we think it's better to run the unit test on the existing kubernetes cluster.

**Comment by sighingnow** [comment]
Closing as not needed.
