### ISSUE TITLE
Support to deploy the vineyard cluster on the kubernetes cluster created by arm machine

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1458]
Describe your problem
---------------------

As titled.

Additional context
------------------

Related to https://github.com/v6d-io/v6d/discussions/1457

**Comment by jingchu000** [comment]
I follow the document， https://v6d.io/notes/cloud-native/deploy-kubernetes.html#create-vineyard-cluster ，Vineyard is managed by the [Vineyard Operator](https://v6d.io/notes/cloud-native/vineyard-operator.html#vineyard-operator) on Kubernetes，vineyard-system      vineyardd-sample-etcd-0                                      0/1     CrashLoopBackOff   
After executing this：
 cat <<EOF | kubectl apply -f -
apiVersion: k8s.v6d.io/v1alpha1
kind: Vineyardd
metadata:
  name: vineyardd-sample
  # don't use default namespace
  namespace: vineyard-system
spec:
  service:
    type: ClusterIP
    port: 9600
  vineyard:
    image: vineyardcloudnative/vineyardd:alpine-latest
    imagePullPolicy: IfNotPresent
EOF

**Comment by jingchu000** [comment]
My computer is a MacBook Pro (13 inch, M22022)

**Comment by dashanji** [comment]
Get it, thanks the info.

**Comment by sighingnow** [comment]
@dashanji Try upgrade the etcd version to latest release in the Dockerfile and test on your MacOS M1.
