### ISSUE TITLE
Vineyard Rust SDK enhancement

### ISSUE THREAD

**Issue by sighingnow** [v6d-io/v6d#1473]
Describe your problem
---------------------

- [x] Basic message protocol
- [x] Status / ErrorCode
- [x] IPCClient / RPCClient
- [x] MMap / shared memory manager
- [ ] Data structure for arrow arrays/recordbatch/tables
- [ ] polars dataframe

Additional context
------------------

See also:
- #273 
- #1332 
- #1504

**Comment by lidh15** [comment]
we have been waiting for it!
