### ISSUE TITLE
Add a benchmark test for kedro-sagemaker and kedro-vineyard

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1487]
Describe your problem
---------------------

Thanks for the advice from @marrrcin via kedro slack, we'd use the [example](https://kedro-sagemaker.readthedocs.io/en/0.3.0/source/03_quickstart.html) of `kedro-sagemaker` as the benchmark example and use `kedro-vineyard` to generate an argo workflow yaml, then submit it to the Kubernetes cluster.

/cc @sighingnow

**Comment by marrrcin** [comment]
It was more a suggestion to compare against the `CloudpickleDataset` from this plugin: https://github.com/getindata/kedro-sagemaker/blob/dbd78fd6c1781cc9e8cf046e14b3ab96faf63719/kedro_sagemaker/datasets.py#L126 not the SageMaker itself. The `CloudpickleDataset` uses a combination of cloudpickle+zstandard to dump/load intermediate data between nodes.

**Comment by dashanji** [comment]
> It was more a suggestion to compare against the `CloudpickleDataset` from this plugin: https://github.com/getindata/kedro-sagemaker/blob/dbd78fd6c1781cc9e8cf046e14b3ab96faf63719/kedro_sagemaker/datasets.py#L126 not the SageMaker itself. The `CloudpickleDataset` uses a combination of cloudpickle+zstandard to dump/load intermediate data between nodes.

Hi, @marrrcin. Thanks for the quick reply, is there any example of how to use the `CloudpickleDataset`? I have checked the doc and repo code, but have no idea about how to use it.

**Comment by marrrcin** [comment]
It's used in the SageMakerRunner as a default dataset implementation, similar to yours: https://github.com/getindata/kedro-sagemaker/blob/dbd78fd6c1781cc9e8cf046e14b3ab96faf63719/kedro_sagemaker/runner.py#L28

**Comment by dashanji** [comment]
Ok, I try to understand it, the command`kedro sagemaker run` will use the `CloudpickleDataset` as the default dataset? Also, the [example](https://kedro-sagemaker.readthedocs.io/en/0.3.0/source/03_quickstart.html) use `CloudpickleDataset` as well?

**Comment by dashanji** [comment]
Ok, I understand it. Thanks.
