### ISSUE TITLE
Vineyard operator can't be deployed successfully with helm chart

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1490]
Describe your problem
---------------------

Get the following debug info.
```
 Warning  FailedMount  108s (x10 over 5m58s)  kubelet            MountVolume.SetUp failed for volume "cert" : secret "vineyard-operator-webhook-server-cert" not found 
 Warning  FailedMount  100s (x2 over 3m55s)   kubelet            Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition
```

**Comment by dashanji** [comment]
Actually, after adding the `--wait` flag, the vineyard operator can't be deployed successfully.

**Comment by dashanji** [comment]
> I have noticed this issue many times. There might be another cert-manager running (maybe in another namespace).

Currently, if another cert-manager exists, vineyard operator helm chart will not be created successfully as the `cert-manager CRD` already exist.

> In my case, after adding the `--wait` flag, the vineyard operator can't be deployed successfully.

If we set the `--wait` flag, the secret `vineyard-operator-webhook-server-cert` will not be created. It looks like we need to wait for [the helm pr](https://github.com/helm/helm/pull/10920) to merge. As a workaround, the users need to delete the `--wait` flag and wait for the operator ready explicitly.

/cc @sighingnow

**Comment by dashanji** [comment]
@sighingnow I'm sorry I didn't find the true reason previously and made some noise.

The current chart uses the helm chart hooks to control the order of deployment as follows:
https://github.com/v6d-io/v6d/blob/56b8202472476857e6b98860603990e6c42fe54e/charts/vineyard-operator/templates/selfsigned-issuer.yaml#L5-L7

https://github.com/v6d-io/v6d/blob/56b8202472476857e6b98860603990e6c42fe54e/charts/vineyard-operator/templates/serving-cert.yaml#L5-L7

From the [helm chart hooks](https://helm.sh/docs/topics/charts_hooks/), we can see the following explanation:
> The library loads the resulting resources into Kubernetes. Note that if the --wait flag is set, the library will wait until all resources are in a ready state and will not run the post-install hook until they are ready.

In a word, If we set the `--wait` flag, the vineyard operator will not be ready as the issuer and cert never suppose to be created. Maybe we need to find a better way to control the execution order of two helm charts, or regard the deployment of cert-manager as a prerequisite.

**Comment by sighingnow** [comment]
Remove `--wait` is ok.

Thanks!

**Comment by sighingnow** [comment]
Add a record in the `FAQ` section of documentation.

**Comment by dashanji** [comment]
Copy.
