### ISSUE TITLE
Add a default value for flags.VineyarddOpts.Vineyard.Size

### ISSUE THREAD

**Issue by zhuyi1159** [v6d-io/v6d#1497]
Describe your problem
---------------------

When I deployed Vineyardd using `deployVineyarddCmd.Run(deployVineyarddCmd, []string{})`, I didn't set the value for `flags.VineyarddOpts.Vineyard.Size`, which caused the pod `vineyardd-sample-69697f5d7f-p7fq4` to continuously crash and restart. The logs of the pod showed the following error: `[error] Check failed: Not enough memory: mmap failed, size = 0 in "root_vs->Serve(StoreType::kDefault)", in function vineyard::Status vineyard::VineyardRunner::Serve(), file /work/v6d/src/server/server/vineyard_runner.cc, line 69`.

After setting `flags.VineyarddOpts.Vineyard.Size`, the pod started successfully. Therefore, `flags.VineyarddOpts.Vineyard.Size` may need to be assigned a default value to avoid such crashes and ensure proper initialization of the Vineyardd pod.

**Comment by zhuyi1159** [comment]
/k8s/cmd/commands/flags/vineyardd_flags.go   line 69

**Comment by zhuyi1159** [comment]
#1498

**Comment by sighingnow** [comment]
@zhuyi1159 Thanks for reporting. Which version of vineyard are you working with?

**Comment by zhuyi1159** [comment]
> @zhuyi1159 Thanks for reporting. Which version of vineyard are you working with?

I am using the latest version v0.16.2 at the moment.

**Comment by sighingnow** [comment]
Cannot reproduce. Defaulting to an empty string is the desired behavior.

Make sure you are working with a correct version of vineyardd.
