### ISSUE TITLE
Python SDK: PUT/GET API for vineyard csi driver

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1555]
Describe your problem
---------------------

The issue is part of https://github.com/v6d-io/v6d/issues/1528, and also as a follow-up of https://github.com/v6d-io/v6d/pull/1533.

During integration with kubeflow, we need to provide a simple PUT/GET API to replace the original IO API(such as read_csv/to_csv/read_parquet/to_parquet and so on). The design is as follows:

vineyard.read('path')

```python

client = vineyard.connect('path/vineyard.sock')
objid = client.get_name(path)
value = client.get(path)
client.close()
return value

```

vineyard.write(value, 'path')

```python

client = vineyard.connect('path/vineyard.sock')
client.put(value, persist=True, name=path)
client.close()

```

**Comment by dashanji** [comment]
Hi @sighingnow, could you please review this?

**Comment by sighingnow** [comment]
Don't close the client. Just leave it as it and there's a connection manager that will manage its lifetime.

**Comment by sighingnow** [comment]
> objid = client.get_name(path)
> value = client.get(path)

client.get(name=...)

**Comment by dashanji** [comment]
> Don't close the client. Just leave it as it and there's a connection manager that will manage its lifetime.

Copy.
