### ISSUE TITLE
Supports mapping multiple vineyard objects to the same volume in the vineyard csi driver

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1568]
Describe your problem
---------------------

Currently, a vineyard object is mapped as a volume. It's nice to support that multiple vineyard objects are mapped under a volume.
However, a PVC can only be bound to a PV, and if there is only one volume, the workloads based on it can be only deployed on the specific node.  Maybe we need some wrappers to do that.

**Comment by dashanji** [comment]
Tested on the CSI Driver, multiple Kubernetes PVCs can't be bound to the same pv. Maybe we need to use the wrappers to rewrite the source code and the generated argo workflow. 

@sighingnow Do you think we need such a feature?

**Comment by sighingnow** [comment]
To mount multiple objects into the same container, you can either

- mount multiple volume
- or, establish a PVC which corresponding to a prefix of object names in vineyard.

**Comment by dashanji** [comment]
> or, establish a PVC which corresponding to a prefix of object names in vineyard.

Suppose we have several paths in the code, such as `/path1/test1.object`, `/path1/test2.object`, `/path2/test3.object`.

If I understand correctly, you mean the PVC is mounted with the common prefix `/path1` and `/path2`, so that we can connect the vineyard cluster by the sockets `/path1/vineyard.sock` and `/path2/vineyard.sock`.
