### ISSUE TITLE
Vineyard-io: `vineyard.io.serialize` API failed in recent CI

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1569]
Describe your problem
---------------------

It looks like the error encountered several times recently. 

/cc @sighingnow 

https://github.com/v6d-io/v6d/actions/runs/6231353460/job/16917803813#step:27:3813
https://github.com/v6d-io/v6d/actions/runs/6231950479/job/16914280878#step:21:490

**Comment by sighingnow** [comment]
Maybe there are some dependency upgrading issues.

I would take a look.

**Comment by dashanji** [comment]
Okay, thanks.

**Comment by dashanji** [comment]
Maybe `fssec`?
