### ISSUE TITLE
GPU shared memory: revision & integration

### ISSUE THREAD

**Issue by sighingnow** [v6d-io/v6d#1582]
Instead of current ad-hoc `UnifiedMemory` abstraction (https://github.com/v6d-io/v6d/blob/main/src/common/memory/gpu/unified_memory.h). We propose:

- A `GPUBlob` type, serve as mirror of `Blob` (and `GPUBlobWrite` which mirrors `BlobWriter`), keep basically same interfaces with current `Blob`, but the pointer only accessible from `__device__` or `__global__`
- A guard type which ensure the GPU memory are propagated (synchronized) back to GPU when the guard finished, e.g., something like:
  
  ```cpp
  {
    auto guard = gpu_blob.shallow(); // gpu_blob.shallow(uninitialized=True);
    auto pointer /* cpu pointer */ = guard.data();
    ...
  }
  ```
- Proper wrapper for Python
- Proper integration with Pytorch
- Data movement between different GPUs using NCCL p2p

**Comment by sighingnow** [comment]
@septicmk any comments?

**Comment by septicmk** [comment]
Is `GPUBlob` still immutable?

**Comment by sighingnow** [comment]
> Is `GPUBlob` still immutable?

I think yes. I have updated the description to add `GPUBlobWriter`.
