### ISSUE TITLE
Integrate with fluid

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1596]
Describe your problem
---------------------

**Motivation**
Use [Fluid](https://github.com/fluid-cloudnative/fluid) as the launcher of vineyard. 

**Detail**
We can leverage the [Thinruntime and Dataset mechanism](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/samples/thinruntime.md) to mount the vineyard socket so that we don't need to deploy the Vineyard CSI Driver anymore.

**Comment by sighingnow** [comment]
Closing as fluid PRs has been merged.
