### ISSUE TITLE
Memory release when use client.delete

### ISSUE THREAD

**Issue by ddebby** [v6d-io/v6d#1620]
Describe your problem
---------------------

I try to delete an object by using the client.delete, but the share memory assgined is not release ?
Is there some way to release share memory?

----------------------------------------------------------------------

**Comment by sighingnow** [comment]
Hi @ddebby,

Thanks for raising the question! May I know more details about the problem you encountered? It would be great if you could show the code snippets or a minimal reproducible example for us!

**Comment by sighingnow** [comment]
A new API called `memory_trim` is added to vineyard client in #1638 to force release the physical memory in unused shared memory regions immediately.

Hope that could be helpful for your questions.
