### ISSUE TITLE
IPC issue: fd set is not matched between client and server

### ISSUE THREAD

**Issue by qiranq99** [v6d-io/v6d#1623]
Hi! 

We have been using `vineyard 0.18.4` on Python 3.8 & Linux 5.15, and encountered an issue on single-machine IPC, e.g., the following codes utilize a parent process to `get` a data object from the socket, which is `put` by a child process:

```
import multiprocessing as mp
import time
import numpy as np
import vineyard

client = vineyard.connect("/tmp/vineyard.sock")

def sub_process_fn(queue):
    data = np.random.randint(1,10,10)
    oid = client.put(data)
    queue.put(oid)
 
queue = mp.Queue()
sub_process = mp.Process(target=sub_process_fn, args=(queue))
sub_process.start()

time.sleep(1)
if not queue.empty():
    item = queue.get()
    sub_process.join()
client.get(item)
```

It would give an error message like: `Unknown error: {"error": "GetBuffers": the fd set is not matched between client and server, "fd_recv": [15], "fd_sent":[], "response": ...}`. 

Any workarounds?

**Comment by dashanji** [comment]
Hi @qiranq99 , thanks for reporting the issue.

A simple workaround is to use the vineyard v0.18.0.

**Comment by qiranq99** [comment]
Thanks for the quick fix. Any ideas on the reasons causing the bug?

**Comment by qiranq99** [comment]
Hi @dashanji , thanks for the quick reply. 

However, the bug still exists on `v0.18.0`.

**Comment by dashanji** [comment]
@qiranq99 Oh, sorry for the mistake. I just tried the code on my own machine and it can work in vineyard v0.18.0.

Also, I have tried the released one and it can't work as you said. We will try to figure it out and reply you ASAP.

**Comment by qiranq99** [comment]
The problem seems to be the producer and the consumer cannot share the same client. Not sure if it should report an error like that but anyway it can be avoided.

**Comment by dashanji** [comment]
Yeah, @qiranq99. It looks like an error caused by the subprocess. Anyway, you could try Vineyard via the [official docs](https://v6d.io/notes/key-concepts/data-accessing.html#local-objects).

**Comment by qiranq99** [comment]
It is still a bug, but a workaround is available for my use case. Let's archive this issue or whatever.

**Comment by dashanji** [comment]
Hi @qiranq99, actually it's caused by the [client set cache](https://github.com/v6d-io/v6d/blob/main/python/client.cc#L84-L89) of the client. In your case, the child process will execute first and set some status to client. After that, the parent process will use the client set cache as it's stored in both child and parent's address space. However, the client status is generated in the child's address space and will not affect the parent's address space. The client status is none for parent process, thus the error occured.

To avoid using the client set cache, you have two choices. One is not to share the client set cache on top of the processes.

```python
import multiprocessing as mp
import time
import numpy as np
import vineyard


def sub_process_fn(queue):
    print('sub process')
    data = np.random.randint(1,10,10)
    client1 = vineyard.connect("/tmp/vineyard.sock")
    oid = client1.put(data)
    queue.put(oid)

queue = mp.Queue()
sub_process = mp.Process(target=sub_process_fn, args=(queue,))
sub_process.start()

time.sleep(1)
if not queue.empty():
    item = queue.get()
    sub_process.join()
client2 = vineyard.connect("/tmp/vineyard.sock")
client2.get(item)
```

Another is to use the `fork` method to create a new client to avoid the cache.

```python
import multiprocessing as mp
import time
import numpy as np
import vineyard


client = vineyard.connect("/tmp/vineyard.sock")
def sub_process_fn(queue):
    print('sub process')
    data = np.random.randint(1,10,10)
    oid = client.fork().put(data)
    queue.put(oid)

queue = mp.Queue()
sub_process = mp.Process(target=sub_process_fn, args=(queue,))
sub_process.start()

time.sleep(1)
if not queue.empty():
    item = queue.get()
    sub_process.join()
client.get(item)
```

**Comment by qiranq99** [comment]
Excellent, problem solved.
