### ISSUE TITLE
Automatic socket management

### ISSUE THREAD

**Issue by qiranq99** [v6d-io/v6d#1625]
Hi, 

In some use cases, we would like `vineyard` to automatically manage the sockets it creates. 

For instance, if a socket is explicitly created via `python3 -m vineyard --socket /tmp/vineyard.sock`, the socket would not be de-constructed after the server has been terminated, while the lifetime management may be supposed to be implicit and automatic.

**Comment by sighingnow** [comment]
The issue has been addressed by #1643.
