### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by qiranq99** [v6d-io/v6d#1631]
Hi, 

Under several benchmarks of putting data object to the shared store (from 1KB to several GBs), we observed that `vineyard` underperforms `ray` (`plasma`), for spending 2x-5x more time

With the data object size getting larger, the performance issue scales. Are there any specific reasons or sources of overhead?

**Comment by sighingnow** [comment]
Which kinds of objects you are working with? Can we know the dtypes/schema if you are working with pandas dataframe/tables.

There's known performance degeneration if your pandas dataframe has string columns.

**Comment by qiranq99** [comment]
Hi, 

basically `numpy` arrays and `torch.tensor` are tested. The performance is not satisfying for both cases, whether small or large data objects.

**Comment by sighingnow** [comment]
Thanks for the information. We'll take a try to verify the result.

**Comment by qiranq99** [comment]
To clarify, the measurements mentioned above are not valid in most cases. The amended benchmarks shows 1.2 ~ 1.5 performance degradation compared with `ray`.

**Comment by qiranq99** [comment]
Additional information:

We compared `vineyard`, bare `plasma`, and `ray`, it appeared that the benchmarking results are like `ray`=`1.2-1.5` `vineyard` or `plasma`. It seems like it is `ray` making some underlying optimizations on the top of the original `plasma`, IMO.

**Comment by dashanji** [comment]
> You could try out putting a `np.random.rand(512,1024,1)` array (4MB), and compare `vineyard.put()` with `ray.put()`. On our machine, the performance is barely 1/4 against `ray`.

I have tested the code and done some profiling, the `vineyard.put` is mainly spent on the memcpy (copy to the shared memory). My guess is that ray use `cython` and vineyard use `pybind` via https://github.com/pybind/pybind11/issues/1227

**Comment by sighingnow** [comment]
Hi @qiranq99,

Actually, the performance gap has nothing to do with the Cython/pybind11 calls. The gap is because plasma internally use multiple threads for concurrent memcpying (by default is 6, see also: https://github.com/apache/arrow/blob/apache-arrow-11.0.0/python/pyarrow/_plasma.pyx#L532) while vineyard uses single thread for memcpy.

After enabling concurrent memcpy, vineyard archives even higher throughput than plasma at the same level of parallelism when putting numpy ndarrays:

```
----------------------------------------------------------------------------------------------- benchmark: 2 tests -----------------------------------------------------------------------------------------------
Name (time in ms)                                  Min                 Max                Mean             StdDev              Median                IQR            Outliers     OPS            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_bench_numpy_ndarray[vineyard_client]     151.3903 (1.0)      171.5272 (1.0)      159.5318 (1.0)       8.8069 (1.0)      154.6269 (1.0)      14.2480 (1.0)           1;0  6.2683 (1.0)           5           1
test_bench_numpy_ndarray[plasma_client]       170.0288 (1.12)     212.2317 (1.24)     190.6309 (1.19)     15.2340 (1.73)     192.0371 (1.24)     16.5868 (1.16)          2;0  5.2457 (0.84)          5           1
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

The benchmark case and newly added concurrency control in Python APIs can be found at #1646.

**Comment by sighingnow** [comment]
The concurrent memcpy is only enabled for copies >= 64MB to optimize the overhead of creating threads.
