### ISSUE TITLE
Update v6d.io use of CNCF logo

### ISSUE THREAD

**Issue by mattfarina** [v6d-io/v6d#1633]
At the bottom of v6d.io there is a CNCF logo. There is a sandbox specific logo that can be found at https://github.com/cncf/artwork/blob/main/examples/other.md#cncf-sandbox-logos. Can you please update the logo to use the sandbox project specific logo.

**Comment by sighingnow** [comment]
Addressed by https://github.com/v6d-io/v6d/pull/1636
