### ISSUE TITLE
v6d.io site source

### ISSUE THREAD

**Issue by mattfarina** [v6d-io/v6d#1634]
I notice this repo exists but has no content for the website found at v6d.io. Can the source for that website be open sourced here?

**Comment by sighingnow** [comment]
Hi @mattfarina,

Thanks for noticing it. The v6d-io/website repo was created for the collaboration with the CNCF service desk for the website designing (see also #1635 (transferred from the website repo)). The effort was merged in #1449 and the source is finally available at https://github.com/v6d-io/v6d/tree/main/docs.

I have archived the v6d-io/website repo as read-only and transfer the issues to this repo.

**Comment by sighingnow** [comment]
Closing as resolved.
