### ISSUE TITLE
Make Vineyard Operator compatible with a certain range of lower versions of k8s

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1651]
Describe your problem
---------------------

### What is the problem:

Recently, when users were running some examples with a lower version of k8s (e,g. 1.23). Some components of vineyard operator can't work as expected.

### The behaviour that you expect to work:

It's better to make vineyard operator compatible with a certain range of lower versions of k8s (1.19~). A possible way is to 
 writer a wrapper, which can build the different images of vineyard operator for different k8s version and push the image as `vineyardcloudnative/vineyard-operator:(vineyard-version)-(k8s-version)` such as `vineyardcloutnative/vineyard-operator:0.19.1-k8s1.19`. Besides, we need to add a flag `k8s.version` to the helm chart.

**Comment by sighingnow** [comment]
> . A possible way is to
writer a wrapper, which can build the different images of vineyard operator for different k8s version and push the image as

Don't do that. The compatibility should be implemented in the source level and the compatiblity (which version range of K8s would work) should be clearly documented.

**Comment by sighingnow** [comment]
Any progress or update on the this issue?

**Comment by dashanji** [comment]
WIP, see also https://github.com/dashanji/v6d/tree/adapt-k8s-1.18
