### ISSUE TITLE
Hive module chores

### ISSUE THREAD

**Issue by vegetableysm** [v6d-io/v6d#1656]
Describe your problem
---------------------

1. Vineyard java sdk currently has dependencies that conflict with hive. （Such as guava）

2. Does the table structure in the vineyard java sdk need to be refactored? 
The data for a hive table can be stored in different files under the same folder. However, the hive tables currently stored on the vineyard are actually stored using multiple vineyard tables (one vineyard table per file). Do we need to refactor the vineyard sdk table structure to match the hive table structure?

3. Optimize the hive module deployment process.

4. Complete hive documentation.  

see at #1682  #1683  #1684

**Comment by sighingnow** [comment]
Please create sub issues for those todos.
