### ISSUE TITLE
Transform Vineyardctl Commands to REST APIs and Develop UI-based Monitor

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#1676]
Describe your problem
---------------------

Objective:
- Convert Vineyardctl commands into REST APIs and create a UI-based monitor to encapsulate these APIs for enhanced interaction and monitoring.

Tasks:
- [ ] Transform vineyardctl commands to RESTful APIs.
- [ ] Develop a backend service that implements these RESTful APIs.
- [ ] Design and implement a user-friendly web-based interface (monitor) that interacts with the REST APIs to provide real-time insights and controls.

**Comment by sighingnow** [comment]
Restful APIs is not a hard requirement for UI-based monitors.

Closing as invalid.
