### ISSUE TITLE
Create llm cache block builder only when the user requests an update.

### ISSUE THREAD

**Issue by vegetableysm** [v6d-io/v6d#1826]
Describe your problem
---------------------

Currently, we will fetch and get a block object if user request a cache block(update or query) and create a builder from this block object. Then delete the block object. There exist an extra memory copy process when create a new builder. We can keep the block object to server the query request from the user and create a new builder only when the user requests an update.

**Comment by sighingnow** [comment]
Has this issue been fixed or not?

**Comment by vegetableysm** [comment]
> Has this issue been fixed or not?
No. We pull block object only when we access the block, but we will rebuild the builder. We can change it to build the builder only for update and serve the query via block in the future.
