### ISSUE TITLE
Vineyard memory was occasionally incompletely recycled when the llm test exited(blob storage)

### ISSUE THREAD

**Issue by vegetableysm** [v6d-io/v6d#1838]
Describe your problem
---------------------

As tittled.

Currently disable vineyard memory usage checks of llm test provisionally.(Fix in the future)

**Comment by sighingnow** [comment]
Is it still an issue? @vegetableysm

**Comment by vegetableysm** [comment]
> Is it still an issue? @vegetableysm

Yes. I try to clean all global object in vineyard after close the cache. But when I use the InstanceStatus interface to query the memory requested by the client, sometimes it is not 0.

**Comment by vegetableysm** [comment]
This module is not currently in use. Close temporarily.
