### ISSUE TITLE
【BUG REPORT】vineyard client.get(object_id) will not timeout and block program while ETCD get down tens of seconds later.

### ISSUE THREAD

**Issue by dzhiwei** [v6d-io/v6d#1947]
**bug report**
vineyard client.get(object_id) will not timeout and block program while ETCD is down(tens of seconds later).
client.get(object_id) cannot work fine, Even when ETCD is Up again and vineyard server reconnected to ETCD.

----------------------------------------------------------------------

1. Operation System version (`uname -a`):
```bash
Ubuntu 22.04
Linux node148 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
2. The version of vineyard you use (`vineyard.__version__`):
0.21.5
4. Versions of crucial packages, such as gcc, numpy, pandas, etc.:
gcc version 11.4.0
numpy                                    1.26.3
pandas                                   1.5.3
5. Full stack of the error (if there are a crash):
client test code log:
```bash
127.0.0.1:30012 -> put value: 42
127.0.0.1:30012 -> get value: 42
127.0.0.1:30012 -> get value: 42
127.0.0.1:30012 -> get value: 42
127.0.0.1:30012 -> get value: 42
127.0.0.1:30012 -> get value: 42
127.0.0.1:30012 -> get value: 42
127.0.0.1:30012 -> get value: 42
```
...blocking

```bash
python3 -m vineyard -rpc_socket_port=30012 --socket=/tmp/vineyard_workspace/vineyard.sock --etcd_endpoint=192.168.0.148:43379 --size=16Gi --etcd_prefix=test
```
vineyard server log:
```bash
I20240718 07:22:27.802374 21962 vineyardd.cc:104] Hello vineyard v0.21.5!
I20240718 07:22:27.807368 21962 meta_service.cc:79] meta service is starting, waiting the metadata backend service becoming ready ...
I20240718 07:22:27.823109 21962 malloc.cc:88] Use memfd_create(2) for shared memory
I20240718 07:22:27.823213 21962 usage.h:596] No spill path set, spill has been disabled ...
I20240718 07:22:27.826387 21962 meta_service.cc:1177] Instance join: 2
I20240718 07:22:27.826411 21962 meta_service.cc:1177] Instance join: 3
I20240718 07:22:27.826424 21962 meta_service.cc:1177] Instance join: 4
I20240718 07:22:27.826436 21962 meta_service.cc:1177] Instance join: 5
I20240718 07:22:27.826535 21962 etcd_meta_service.cc:360] start background etcd watch, since 330
I20240718 07:22:27.828744 21962 meta_service.cc:567] Decide to set rank as 6
I20240718 07:22:27.830309 21962 ipc_server.cc:137] Vineyard will listen on "/tmp/vineyard_workspace/vineyard.sock" for IPC
I20240718 07:22:27.830329 21962 rpc_server.cc:53] Vineyard will listen on 0.0.0.0:30012 for RPC
I20240718 07:22:27.830341 21962 meta_service.cc:1177] Instance join: 6
E20240718 07:26:27.846727 21962 meta_service.cc:642] Instance 2 timeout
I20240718 07:26:27.850442 21962 meta_service.cc:1182] Instance exit: 2
I20240718 07:28:47.561143 22632 etcd_meta_service.cc:382] Watcher stopped, as cancelled: false
I20240718 07:28:57.561259 21962 etcd_meta_service.cc:413] retrying to connect etcd ...
I20240718 07:28:57.561290 21962 etcd_meta_service.cc:360] start background etcd watch, since 354
E20240718 07:28:57.561494 21962 meta_service.cc:1209] Error in daemon watching: Etcd error: failed to create a watch connection, error code: 1
E20240718 07:29:27.857735 21962 meta_service.cc:614] Failed to refresh self: Etcd error: connections to all backends failing, error code: 14
E20240718 07:30:27.858186 21962 meta_service.cc:614] Failed to refresh self: Etcd error: connections to all backends failing, error code: 14
E20240718 07:31:27.858639 21962 meta_service.cc:614] Failed to refresh self: Etcd error: connections to all backends failing, error code: 14
I20240718 07:32:27.861191 21962 meta_service.cc:1177] Instance join: 3
I20240718 07:32:27.861243 21962 meta_service.cc:1177] Instance join: 4
I20240718 07:32:27.861256 21962 meta_service.cc:1177] Instance join: 5
I20240718 07:32:27.861269 21962 meta_service.cc:1177] Instance join: 6
```
6. Minimized code to reproduce the error:
```bash
import vineyard
import numpy as np
import time

if __name__ == "__main__":

    tcp_endpoints = [
        "127.0.0.1:30012",
    ]
    k = "version"
    int_value = 42
    obj_dict = {}
    for vineyard_tcp_endpoint in tcp_endpoints:
        client = None
        host_port_arr = vineyard_tcp_endpoint.split(":")
        try:
            # int_value += 1
            client = vineyard.connect(host=host_port_arr[0], port=host_port_arr[1])
            array = np.array([int_value])
            object_id = client.put(array)
            obj_dict[vineyard_tcp_endpoint] = object_id
            # client.persist(object_id)
            # client.put_name(object_id, k)
            print(f"{vineyard_tcp_endpoint} -> put value: {int_value}")
        except Exception as e:
            print(f"Failed to connect to vineyard by host={host_port_arr[0]}, port={host_port_arr[1]}: {str(e)}")
        finally:
            if client is not None:
                client.close()
    
    client_dict = {}
    
    for vineyard_tcp_endpoint in tcp_endpoints:
        host_port_arr = vineyard_tcp_endpoint.split(":")
        client = vineyard.connect(host=host_port_arr[0], port=host_port_arr[1])
        client_dict[vineyard_tcp_endpoint] = client
    while True:
        for vineyard_tcp_endpoint in tcp_endpoints:
            client:vineyard.RPCClient = client_dict[vineyard_tcp_endpoint]
            retrieved_array = client.get(obj_dict[vineyard_tcp_endpoint])
            retrieved_int_value = retrieved_array[0]
            print(f"{vineyard_tcp_endpoint} -> get value: {retrieved_int_value}")
        time.sleep(6)
```

----------------------------------------------------------------------

------------------

python thread.join(timeout) will not work as expected when target function try to use client.get(object_id) with ETCD down. No timeout error and program will not go on after given timeout time passed.

**Comment by dashanji** [comment]
Hi @dzhiwei. Thanks for raising this issue. We have introduced a timeout for the vineyard client via https://github.com/v6d-io/v6d/pull/1863, could you please try the next version(v0.22.0+)?

**Comment by dzhiwei** [comment]
Thanks. I will try the new version.

**Comment by dashanji** [comment]
> @dashanji great, I can get a timeout error(with 0.22.2) after vineyard server cannot connect to ETCD. And does vineyard C++ client has the similar fix?

Yes, it works for both C++ and python, as the python client will call the related C++ code via pybinding.

**Comment by dashanji** [comment]
Hi @dzhiwei. If you have any questions, please feel free to open it.

**Comment by dzhiwei** [comment]
It works, please close the issue. Thank you!

**Comment by dashanji** [comment]
> @dashanji Please also check another case: when Etcd is back and vineyard server reconnect to etcd(we didn't restart vineyard server). It figures out vineyard server cannot support client to get object, an error will always be thrown. (So we need to restart vineyard server once we encounter this Etcd down/restart case.) tested vineyard 0.22.2,
> 
> ```shell
> Traceback (most recent call last):
>   File "/tmp/testingdata/fabarta-graphscope/test_v6d.py", line 44, in <module>
>     retrieved_array = client.get(obj_dict[vineyard_tcp_endpoint])
>   File "/usr/local/lib/python3.10/dist-packages/vineyard/core/client.py", line 756, in get
>     return get(self, object_id, name, resolver, fetch, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/vineyard/core/resolver.py", line 235, in get
>     obj = client.get_object(object_id, fetch=fetch)
>   File "/usr/local/lib/python3.10/dist-packages/vineyard/core/client.py", line 556, in get_object
>     return self._fetch_object(object_id, enable_migrate=fetch)
>   File "/usr/local/lib/python3.10/dist-packages/vineyard/core/client.py", line 635, in _fetch_object
>     meta = self.get_meta(object_id, sync_remote=True)
>   File "/usr/local/lib/python3.10/dist-packages/vineyard/core/client.py", line 571, in get_meta
>     return self.default_client().get_meta(object_id, sync_remote)
> vineyard._C.IOErrorException: IOError: Select call timeout: Success
> ```
> 
> 0.23.2
> 
> ```shell
> Traceback (most recent call last):
>   File "/tmp/testingdata/fabarta-graphscope/test_v6d.py", line 44, in <module>
>     retrieved_array = client.get(obj_dict[vineyard_tcp_endpoint])
>   File "/usr/local/lib/python3.10/dist-packages/vineyard/core/client.py", line 756, in get
>     return get(self, object_id, name, resolver, fetch, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/vineyard/core/resolver.py", line 235, in get
>     obj = client.get_object(object_id, fetch=fetch)
>   File "/usr/local/lib/python3.10/dist-packages/vineyard/core/client.py", line 556, in get_object
>     return self._fetch_object(object_id, enable_migrate=fetch)
>   File "/usr/local/lib/python3.10/dist-packages/vineyard/core/client.py", line 642, in _fetch_object
>     cluster_info = self.default_client().meta
> vineyard._C.IOErrorException: IOError: Select call timeout: Success
> ```

Hi @dzhiwei, 

Thanks for raising this case. We have fixed it in https://github.com/v6d-io/v6d/pull/1961. 
When the etcd is down, the vineyardd server will keep retrying to connect until it's back.
