### ISSUE TITLE
client.get return a wrong value when put a big integer number

### ISSUE THREAD

**Issue by wangsq** [v6d-io/v6d#2000]
Describe your problem
---------------------

client.get return a wrong value when put a big integer number which larger than 2^63 . Here is the code:

## 1.   put a int smaller than 2^63, this result is same as put value 
```

value = 2**63-1
oid = client.put(value)

result = client.get(oid)
print(f'{value=}, {result=}, {value == int(result)}')
```

output:
`value=9223372036854775807, result=9223372036854775807, True`

## 2. put a int that larger or equal than 2^63, this result is always 1.

```
value = 2**63
oid = client.put(value)

result = client.get(oid)
print(f'{value=}, {result=}, {value == int(result)}')
```
output:
`value=9223372036854775808, result=1, False`

----------------------------------------------------------------------

If is is a **bug report**, to help us reproducing this bug, please provide information below:

1. Your Operation System version (`uname -a`):  6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug fd 11                                                     │Dumping 301618 Realtime Data.  │ 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

2. The version of vineyard you use (`vineyard.__version__`): '0.24.2'

3. Versions of crucial packages, such as gcc, numpy, pandas, etc.:
4. Full stack of the error (if there are a crash):
5. Minimized code to reproduce the error: see above

**Comment by dashanji** [comment]
Duplicated with https://github.com/v6d-io/v6d/issues/1999, closed.
