### ISSUE TITLE
Support the Date type in arrow when reading from csv.

### ISSUE THREAD

**Issue by siyuan0322** [v6d-io/v6d#236]
- [x] Support the new time unit called `Date32Type` and `Date64Type` added in Arrow 3.0 ( #439 ).
- [ ] Currently timestamp are stored as `int64_t` in [graphscope](https://github.com/alibaba/GraphScope), which lost the time unit information. We may want to support the full functionality of timestamp.
- [ ] Complex data types, e.g., String, Date, Timestamp and List and Structure not supported yet in the C++ and Python SDK. The missing pieces limits some real world applications, and should be filled in a well-designed approach

**Comment by tushar5526** [comment]
Hi! I am interested in adding the missing data-types. Can you provide some information and a heads-up to get started?
Thanks

**Comment by siyuan0322** [comment]
Hi, @tushar5526 , Thanks for your attention to vineyard! 
As the description says, vineyard aims to align with Apache-arrow with its data types, and we have implemented some data structure like Table / PrimitiveArray / LargeStringArray, etc, it's would be better if we could managed to add the remaining types such as Timestamp / Date / List etc.
Vineyard can store and access these data structures in a zero-copy manner across language and processes, understanding the memory layout of arrow's data structures is key to this objective.
And please note this issue also related to #248 as well.

**Comment by sighingnow** [comment]
Closing as extending the arrow CSV parser part would be tracked by #761 and the complex types, e.g., list types has already been supported in places like shuffle, transform, and outputing.
