### ISSUE TITLE
Extend arrow csv parser to support read list arrays.

### ISSUE THREAD

**Issue by siyuan0322** [v6d-io/v6d#248]
**Is your feature request related to a problem? Please describe.**
We may want to parse `arrow::LargeListArray` from csv files. 
The raw format could be `[1, 2, 3, 4]`, and the parsed array type should be `arrow::large_list(arrow::int64())`.

**Comment by sighingnow** [comment]
Related to #247.

**Comment by sighingnow** [comment]
Related to #236 as well.

**Comment by sighingnow** [comment]
We can get some ideas of supporting list/nested types with tsv/csv from https://clickhouse.com/docs/en/interfaces/formats/#tabseparated

**Comment by sighingnow** [comment]
Closing as replaced by #761.
