### ISSUE TITLE
Flexible parameter to set shared memory limit that vineyard can use.

### ISSUE THREAD

**Issue by sighingnow** [v6d-io/v6d#316]
**Describe your problem**

In the current implementation, we specify a `--size` for maximum shared memory size that vineyard daemon can use. However, it is just a SOFT limit. And,

When there's no enough shared memory (i.e., size of `/dev/shm` path) the limit doesn't make sense. And when users exceed the memory limit, a BUS error will occur at the client side, and crashes the program.

We need to check the maximum shared memory size first, and raise a warning (n.b.: not a failure) to users when it less than the soft limit in the `--size` parameters.

**Comment by Rohan-cod** [comment]
Hi @sighingnow, I would like to work on this issue. Please guide me through it.

**Comment by sighingnow** [comment]
We have a bulk allocator (https://github.com/v6d-io/v6d/blob/main/src/server/memory/allocator.cc#L50) in vineyardd. The initialize size comes from the command-line argument `--size`, which, however, may exceed the limitation of system's shared memory size, i.e., the size of `/dev/shm` on Linux.

This task is to add a check here, and for invalid user input, raise a warning.

**Comment by sighingnow** [comment]
I have reviewed the PR #321, but I think such a check should be placed in vineyard server.
