### ISSUE TITLE
Associate a backtrace to erroneous Status

### ISSUE THREAD

**Issue by sighingnow** [v6d-io/v6d#326]
**Describe your problem**

Vineyard returns `Status` when error occurs, and we have things like `VINEYARD_CHECK_OK` to act as assertions to check pre/post conditions in both the client and the server.

However, from the `Status` it is still hard to know what unexpected happens and is not every easy for debugging. We have a set of constructors in `Status` to construct a status. It would be good to associate a backtrace into the Status, at least under debug mode.

We have do similar things in [`RETURN_GS_ERROR`](https://github.com/v6d-io/v6d/blob/main/modules/graph/utils/error.h#L121) and we definitely could do more.

**Additional context**

**Comment by peilii** [comment]
Hi @sighingnow, I would like to work on this issue.

**Comment by sighingnow** [comment]
Thanks! I would assign this issue to you.

**Comment by sighingnow** [comment]
The `Status` is defined in https://github.com/v6d-io/v6d/blob/main/src/common/util/status.h.

Adding backtrace in `VINEYARD_CHECK_OK/VINEYARD_ASSERT/...` or in the `Status::Status()` both ok to me.

**Comment by sighingnow** [comment]
You may need to add a new filed `backtrace` and a method `Status::Backtrace()`.

**Comment by peilii** [comment]
Got it, thanks!
