### ISSUE TITLE
Graceful clean-up on bulk store: "free" the memory when exit.

### ISSUE THREAD

**Issue by sighingnow** [v6d-io/v6d#333]
Describe your problem
---------------------

Vineyard server (`vineyardd`) holds all memory blocks allocated by the client. At exit there are still memory chunks that are not freed.

If vineyardd itself is gracefully exits (receiving a `CTRL-C` signal), it would be better to free those shared memory segments as well.

----------------------------------------------------------------------

If it is a **feature request**, please provides a clear and concise description of what you want to happen:

1. What is the problem:

   Shared memory is not freed when exit.

2. The behavior that you expect to work:

   There should be no "memory leaks", and can be checked via a memory sanitizer / address sanitizer, see also #302. 

Additional context
------------------

**Comment by peilii** [comment]
Hi @sighingnow . I would like to work on this issue.

**Comment by sighingnow** [comment]
Hi @peilii I have assigned this issue to you, and it is related to #302 as well.

**Comment by sighingnow** [comment]
> 1. In order to get current objects in all arenas of shared memory, I created a method in class `BulkStore` named `GetArenas`, it is implemented as follows:
> 
> ```
> const std::unordered_map<int, Arena> GetArenas() const { return arenas_; }
> ```
> 
> 2. After getting all arenas in the server, now I am able to get them in `vineyardd_signal_handler` in vineyardd.cc, and by iterate the map I can get all objects in `arena.spans`, and call Delete in Bulkstore as follows:
> 
> ```
> VINEYARD_CHECK_OK(server_ptr_->GetBulkStore()->Delete(object));
> ```
> 

I think in this issue you don't need to warry about the arneas.

To deleting those blobs, just call iterate the `object_` member of the `BulkStore` class and call "Delete" in the dtor (destructor) of `BulkStore` should be enough.

**Comment by peilii** [comment]
> > 1. In order to get current objects in all arenas of shared memory, I created a method in class `BulkStore` named `GetArenas`, it is implemented as follows:
> > 
> > ```
> > const std::unordered_map<int, Arena> GetArenas() const { return arenas_; }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. After getting all arenas in the server, now I am able to get them in `vineyardd_signal_handler` in vineyardd.cc, and by iterate the map I can get all objects in `arena.spans`, and call Delete in Bulkstore as follows:
> > 
> > ```
> > VINEYARD_CHECK_OK(server_ptr_->GetBulkStore()->Delete(object));
> > ```
> 
> I think in this issue you don't need to warry about the arneas.
> 
> To deleting those blobs, just call iterate the `object_` member of the `BulkStore` class and call "Delete" in the dtor (destructor) of `BulkStore` should be enough.

Got it, thanks!
