### ISSUE TITLE
Compiling Error in Ubuntu 20.04

### ISSUE THREAD

**Issue by linlih** [v6d-io/v6d#339]
Describe your problem
---------------------

According to install manual in : https://v6d.io/notes/install.html
The project canot build successful in Ubuntu 20.04，Got an error as follows:
![image](https://user-images.githubusercontent.com/35171741/123567930-d24aaa00-d7f5-11eb-95b6-05cc7f120d2d.png)

**Comment by sighingnow** [comment]
Duplicate with #325.

**Comment by linlih** [comment]
I not quite sure about the version of apache arrow, I using following command to install:
```bash
wget https://bintray.com/apache/arrow/download_file?file_path=ubuntu%2Fapache-arrow-archive-keyring-latest-disco.deb \
    -O /tmp/apache-arrow-archive-keyring-latest-disco.deb
apt install -y /tmp/apache-arrow-archive-keyring-latest-disco.deb
apt update -y	
apt install -y libarrow-dev
```
After install, the system contains serveral lib file in this directory: 
![image](https://user-images.githubusercontent.com/35171741/123571644-3f157280-d7fd-11eb-82bb-2b935957d60a.png)

**Comment by sighingnow** [comment]
You have installed to different version of libarrow-dev at the same time, one is `libarrow.so.16` and another is `libarrow.so.400`.

Vineyard requires `libarrow-dev>=0.17`. I suggest you uninstall both of them, and install a newer version instead:

```
apt-get purge libarrow-dev libarrow16 libarrow400
```

And the reinstall (note that apache arrow has deprecated the usage of bintray and move to jfrog, https://arrow.apache.org/install/):

```
apt install -y -V ca-certificates lsb-release wget
wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
apt update
apt install -y -V libarrow-dev
```

**Comment by sighingnow** [comment]
We have updated our documentation in #340.
