### ISSUE TITLE
Still Cannot compile successful in Ubuntu 20.04

### ISSUE THREAD

**Issue by linlih** [v6d-io/v6d#345]
Describe your problem
---------------------
#339  I have reinstall the libarrow, still compile error.

![image](https://user-images.githubusercontent.com/35171741/123633548-ee793600-d84b-11eb-8cbe-79458f890051.png)

I check the file libvineyard_basic.so, it did link to libarrow.so.400, and this file contains the sysmbol, Maybe the problem will be compile flag didnot contains -larrow?
![image](https://user-images.githubusercontent.com/35171741/123633901-5cbdf880-d84c-11eb-9dc7-3b64f7767209.png)

![image](https://user-images.githubusercontent.com/35171741/123633942-66476080-d84c-11eb-93f1-a5b978eb2a7f.png)

**Comment by sighingnow** [comment]
Thanks for reporting. Will investigate it further.

**Comment by sighingnow** [comment]
Hi @linlih,

I still cannot reproduce the problem on Ubuntu 20.04.

Have you removed the `build` directory and rerun `cmake` after reinstall the libarrow-devel package? We do have linked against arrow libs to those targets: https://github.com/v6d-io/v6d/blob/main/modules/io/CMakeLists.txt#L52

**Comment by linlih** [comment]
I try delete the whole project, and clone a new one to build.
It stops as follow, the whole vmware machine crashed
![image](https://user-images.githubusercontent.com/35171741/123793507-5abf6c80-d914-11eb-8a12-e8bc695ca442.png)

**Comment by linlih** [comment]
I try make it again, using `make` command not `make -j`， finally it compiled success.
I believe the compiling system‘s robustness need to improved.
![image](https://user-images.githubusercontent.com/35171741/123882887-5c238000-d97a-11eb-9450-39eacf5dce3b.png)

**Comment by sighingnow** [comment]
> It stops as follow, and the whole vmware machine crashed, using make -j command

I will revisit all occurrence of `make -j` with `make -j$(nproc)` to avoid such kind of failures on VM and docker.

The `__itt_task_begin_ptr` error looks strange to me ...
