### ISSUE TITLE
Failed to start vineyardd without sudo

### ISSUE THREAD

**Issue by univerone** [v6d-io/v6d#408]
Describe your problem
---------------------

A clear and concise description of what your problem is. It might be a bug,
a feature request, or just a problem that need support from the vineyard team.

----------------------------------------------------------------------

If is is a **bug report**, to help us reproducing this bug, please provide information below:

1. Your Operation System version (`uname -a`): Ubuntu 20.04
2. The version of vineyard you use (`vineyard.__version__`): 0.2.6
3. Versions of crucial packages, such as gcc, numpy, pandas, etc.: 
4. Full stack of the error (if there are a crash): 

```
I0804 15:34:19.528898 114923 vineyardd.cc:86] Hello vineyard!
0x0000000000B9EEC8: (SP:0x00007FFF1D235140) (vineyard::backtrace_on_terminate() + 0x148)

0x00007F53F62AB38C: (SP:0x00007FFF1D235310) (std::rethrow_exception(std::__exception_ptr::exception_ptr) + 0x7C)

0x00007F53F62AB3F7: (SP:0x00007FFF1D235320) (std::terminate() + 0x17)

0x00007F53F62AB6A9: (SP:0x00007FFF1D235330) (__cxa_throw + 0x49)

0x00000000007EBA89: (SP:0x00007FFF1D235350) (void boost::throw_exception<boost::system::system_error>(boost::system::system_error const&) + 0x59)

0x00000000007F5453: (SP:0x00007FFF1D235380) (boost::asio::detail::do_throw_error(boost::system::error_code const&, char const*) + 0x1A3)

0x00000000007DD1E3: (SP:0x00007FFF1D2354E0) (boost::asio::detail::throw_error(boost::system::error_code const&, char const*) + 0x33)

0x00000000007D1F38: (SP:0x00007FFF1D235500) (_ZN5boost4asio21basic_socket_acceptorINS0_5local15stream_protocolENS0_8executorEEC2INS0_10io_contextEEERT_RKNS2_14basic_endpointIS3_EEbPNSt9enable_ifIXsr14is_convertibleIS9_RNS0_17execution_contextEEE5valueEvE4typeE + 0x528)

0x00000000007CAE74: (SP:0x00007FFF1D2357C0) (vineyard::IPCServer::IPCServer(std::shared_ptr<vineyard::VineyardServer>) + 0x284)

0x000000000091BE4D: (SP:0x00007FFF1D2359A0) (vineyard::VineyardServer::Serve() + 0x2FD)

0x0000000000BA011C: (SP:0x00007FFF1D235DE0) (main + 0x99C)

0x00007F53F5EA0CB2: (SP:0x00007FFF1D2365E0) (__libc_start_main + 0xF2)

0x000000000068150E: (SP:0x00007FFF1D2366B0) (_start + 0x2E)

backtrace: unhandled exception std::exception:what(): bind: Permission denied

Process finished with exit code 1

```
5. Minimized code to reproduce the error: `./vineyardd`

----------------------------------------------------------------------

If it is a **feature request**, please provides a clear and concise description of what you want to happen:

### What is the problem:

Failed to start vineyardd without sudo

```bash
./vineyardd
```

### The behaviour that you expect to work:

The vineyardd server be started without error

------------------

**Comment by sighingnow** [comment]
It is not about sudo, it is because the default socket is located at `/var/run/vineyard.sock`, which requires sudo. You could run vineyardd with `sudo`, or, specifying another location for vineyard socket, as `vineyardd --socket=/tmp/vineyard.sock`, it should work as expected.

**Comment by univerone** [comment]
Thanks! It did work

> It is not about sudo, it is because the default socket is located at `/var/run/vineyard.sock`, which requires sudo. You could run vineyardd with `sudo`, or, specifying another location for vineyard socket, as `vineyardd --socket=/tmp/vineyard.sock`, it should work as expected.
