### ISSUE TITLE
Failed to start vineyardd on Mac

### ISSUE THREAD

**Issue by fyrestone** [v6d-io/v6d#448]
Describe your problem
---------------------
``` python
import vineyard

print(vineyard.__version__)
d = vineyard.deploy.local.start_vineyardd()
d.__enter__()
```

Traceback:
```text
0.2.6
dyld: Library not loaded: @rpath/libgrpc.16.dylib
  Referenced from: /Users/admin/.pyenv/versions/3.8.2/lib/python3.8/site-packages/vineyard/.dylibs/libgrpc++.1.38.1.dylib
  Reason: image not found
Traceback (most recent call last):
  File "/Users/admin/v6d_example.py", line 5, in <module>
    d.__enter__()
  File "/Users/admin/.pyenv/versions/3.8.2/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/admin/.pyenv/versions/3.8.2/lib/python3.8/site-packages/vineyard/deploy/local.py", line 130, in start_vineyardd
    raise RuntimeError('vineyardd exited unexpectedly with code %d, error is:\n%s' % (rc, err))
RuntimeError: vineyardd exited unexpectedly with code -6, error is:
```

```bash
ll  /Users/admin/.pyenv/versions/3.8.2/lib/python3.8/site-packages/vineyard/.dylibs

...
-rw-r--r--  1 admin  staff   164K  8 18 10:54 libgpr.16.0.0.dylib
-rw-r--r--  1 admin  staff   648K  8 18 10:54 libgrpc++.1.38.1.dylib
-rw-r--r--  1 admin  staff   3.4M  8 18 10:54 libgrpc.16.0.0.dylib <---- The file name is not matched.
-rw-r--r--  1 admin  staff   2.3M  8 18 10:54 libprotobuf.28.dylib
-rw-r--r--  1 admin  staff   386K  8 18 10:54 libre2.9.0.0.dylib
-rw-r--r--  1 admin  staff   491K  8 18 10:54 libssl.1.1.dylib
-rw-r--r--  1 admin  staff   118K  8 18 10:54 libupb.16.0.0.dylib
-rwxr-xr-x  1 admin  staff   1.9M  8 18 10:54 libvineyard_client.dylib*
```

A clear and concise description of what your problem is. It might be a bug,
a feature request, or just a problem that need support from the vineyard team.

----------------------------------------------------------------------

If is is a **bug report**, to help us reproducing this bug, please provide information below:

1. Your Operation System version (`uname -a`): macOS Catalina 10.15.7
2. The version of vineyard you use (`vineyard.__version__`): 0.2.6
3. Versions of crucial packages, such as gcc, numpy, pandas, etc.
4. Full stack of the error (if there are a crash):
5. Minimized code to reproduce the error:

----------------------------------------------------------------------

If it is a **feature request**, please provides a clear and concise description of what you want to happen:

### The behaviour that you expect to work:

Additional context
------------------

**Comment by fyrestone** [comment]
vineyard is installed by `pip install vineyard`

**Comment by sighingnow** [comment]
It should be a bug in our wheel release, thanks for reporting!

**Comment by sighingnow** [comment]
Hi @fyrestone,

I have uploaded newer version of `whl` package on pypi and the issue should be resolved. You could upgrade your vineyard installation using `pip`:

```
pip uninstall vineyard
pip install -U vineyard -i https://pypi.org/simple
```

Free to comment if there still troubles to launch vineyardd.

**Comment by fyrestone** [comment]
> pip install -U vineyard -i https://pypi.org/simple

Thanks for the quick fix. It works!

**Comment by sighingnow** [comment]
> > pip install -U vineyard -i https://pypi.org/simple
> 
> Thanks for the quick fix. It works!

Thank you for the quick response!
