### ISSUE TITLE
Clarification about lifetime for XCOM in Airflow

### ISSUE THREAD

**Issue by vlavorini** [v6d-io/v6d#586]
Hello,

how much time will the data in XCOM stay before getting deleted? Or maybe a manual process is required for that? And how?

Thank you!

**Comment by sighingnow** [comment]
To clearify the lifetime of objects in XCom I would like to introduce how we implments the XCom backend first.

+ for `set`, we first put the object into vineyard, then store the identifier (vineyard's `ObjectID`) to the DB of airflow
+ for `get`, we first query the identifier from airflow DB, then get the object from vineyard

Thus, for `.clear()/.delete()`, the vineyard xcom exactly inherits the same behaviour with the data lifetime in airflow. When deleting dag runs from airflow, its data will be deleted from vineyard as well.

**Comment by vlavorini** [comment]
Got it, thank you.

So maybe it worths to specify that an XCOM cleaning procedure is to be foreseen since the available memory is in general much smaller than the DB or other backends, and that could lead to `vineyard._C.NotEnoughMemoryException: Not enough memory:` errors.

As example [here](https://stackoverflow.com/questions/46707132/how-to-delete-xcom-objects-once-the-dag-finishes-its-run-in-airflow)

**Comment by sighingnow** [comment]
Thanks for the suggestion. Such a hook looks pretty promising! I will try it out.
