### ISSUE TITLE
C++ projects using vineyard to store shared data

### ISSUE THREAD

**Issue by lszChain** [v6d-io/v6d#590]
Hi! I'm wondering if you're considering the C++ SDK. I've been bothered for a long time with C++ projects using vineyard to store shared data, such as vectors, maps, and custom types. It seems that there is a client module in the source code that can meet my requirements, but I still don't know how to use it. Do I need to extend the client code to support the data types I need to store?

**Comment by sighingnow** [comment]
Hi @lszChain,

My apology for the late response.

> Do I need to extend the client code to support the data types I need to store?

No, you don't need to do such things. I would to fill a tuturial doc today to tell the steps to makes the client the support custom data structures, and the detail of internal design.

It's an issue of missing docs.

**Comment by lszChain** [comment]
It's ok! Looking forward to the detailed doc! We really need!

**Comment by sighingnow** [comment]
> It's ok! Looking forward to the detailed doc! We really need!

Hi @lszChain,

I have add the doc in #592 and it can be found at https://v6d.io/tutorials/adding-custom-datatypes-cpp.html

More detail doc about the internal design will be added later. Thanks for your patience!
