### ISSUE TITLE
[Compatibility] lifecycle management for plasma blobs

### ISSUE THREAD

**Issue by septicmk** [v6d-io/v6d#667]

**Comment by sighingnow** [comment]
> Disconnect() is special, the client will release all the object_id it keeps.

Should be `the server will release all ...`

> calling client.Release(O1) will result B1.ref_cnt == 0. if B1 is going to be evicted. O1 should be evicted too, but B2 should be reserved( ref_cnt > 0).

I suggest restrict the "Release" op to blob only.
