### ISSUE TITLE
Spilling: dump cold blobs when memory is full in Allocation.

### ISSUE THREAD

**Issue by septicmk** [v6d-io/v6d#740]
Describe your problem
---------------------

Support `spill` and `reload` functionality for blobs. Intuitively we can store a `BlobFault` flag for the cold blobs in our memory storage, and trigger the reload callback when we touch them.

**Comment by ZjuYTW** [comment]
I have an preliminary idea for the `spill` and `reload`
Firstly, for spilling, based on the previous step we have a `LRU` to track the unused object[1]. Whenever we have the oom detected[2] we spill the object to disk by dumping the memory (we have the address and the size stored in Payload) into disk[3].  As mentioned in the issue, we may have a `Blobfault` flag to trigger the callback of reload. To achieve this, one simple way to do this is to keep a `spilled` map  of <ObjID, callback> and check it whenever we have a GetBuffer request.

Second, for reloading, we should find another memory block to store the object, and to complete this, we could reused the previous logic to find a victim block.

So there are three main question:
[1] : If we have the LRU that just track every different-sized objects, we may need to iterate through list to find the fit-most memory-hole? And there may exist `memory fragment`.
[2]: How do we detect oom? From what I have read from the source code that the system use memory allocator to manage the memory allocation (eg. dlmalloc), and should we use the `Status::NotEnoughMemory` to decide the time to spill? 
[3]: To spill the Object, we should create a new file named by objectID and dump the memory into it. I'm wondering if there are better way to do it...

**Comment by septicmk** [comment]
Hi @ZjuYTW, thanks for your proposal! The design looks good to me. 

> [1] : If we have the LRU that just track every different-sized objects, we may need to iterate through list to find the fit-most memory-hole? And there may exist memory fragment.

We do need to iterate through the list to spill enough objects until the memory usage is below a preset threshold. 

>  [2]: How do we detect oom? From what I have read from the source code that the system use memory allocator to manage the memory allocation (eg. dlmalloc), and should we use the Status::NotEnoughMemory to decide the time to spill?

vineyardd sets the memory limitation at [here](https://github.com/v6d-io/v6d/blob/85d75514eb4f706821c6aa787f6c12cc7f3b630d/src/server/server/vineyard_server.cc#L110) and the the OOM exception is thrown at [here](https://github.com/v6d-io/v6d/blob/85d75514eb4f706821c6aa787f6c12cc7f3b630d/src/server/memory/memory.cc#L457)

> To spill the Object, we should create a new file named by objectID and dump the memory into it. I'm wondering if there are better way to do it...

To support configurable spilling behavior, we could add three FLAGs at [spec_resolvers.cc](https://github.com/v6d-io/v6d/blob/85d75514eb4f706821c6aa787f6c12cc7f3b630d/src/server/util/spec_resolvers.cc)
- a `spilling_directory` to specify a writable path.
- a `max_spilling_threshold` to trigger spilling when memory usage is larger than it.
- a `min_spilling_threshold` to stop spilling when memory usage is below than it.
