### ISSUE TITLE
FileSystem view of shared objects inside vineyard cluster

### ISSUE THREAD

**Issue by sighingnow** [v6d-io/v6d#760]
Describe your problem
---------------------

Vineyard provides in-memory object sharing between computing engines, allowing them to obtain the shared objects in a zero-copy fashion. Vineyard provides a convenient API (i.e., `get`/`put`) and an extensible mechanism (i.e., `builder`/`resolver`) to allow computing engines integrating with vineyard to leverage vineyard's object sharing capability. 

Such integration enables efficient data sharing to avoid the cost of copying and data serialization/deserialization. However, the integration might be a bit intrusive and increases the complexity of deploying in various environments. Most computing engines have a file-oriented IO interface to interact with data sources and sinks thus providing a file view of shared objects in vineyard cloud significantly reduces the cost of integration with not much performance overhead.

This task is to implement a general filesystem view for shared objects in vineyard which allows the client read the objects just like reading a file. E.g.,

- A blob can be efficiently viewed as a blob file
- A tensor can be efficiently viewed as [a `npy` file](https://numpy.org/doc/stable/reference/generated/numpy.save.html)
- A dataframe can be efficiently viewed as HDF5, parquet, or ORC file

Note that in vineyard data types are formed in a hierarchical structure, e.g., a tensor is built upon a blob, and a dataframe is built upon a set of tensors (as columns).

The filesystem view can be implemented using fuse, which mounts a given vineyard cluster to a mount point (a directory) and allows compute engines to read data using file IO.

As described above, an object of a certain type (e.g., a dataframe) can be viewed as various formats of files (i.e., HDF5, parquet, ORC). Fortunately, an overlay layered design could be helpful, as we first implement a basic layer that supports only blobs. Upon the basic layer, those blobs can be composed into more complicated data types, e.g., tensors and dataframes.

Vineyard already has some experiments on the FUSE support and can be found at https://github.com/v6d-io/v6d/tree/main/modules/fuse

Additional context
------------------

This issue is part of our [Alibaba Summer of Code 2022 Program](https://github.com/v6d-io/v6d/issues/758).

- Difficulty: Hard
- Mentor: Tao He (@sighingnow)

**Comment by liusitan** [comment]
Has anyone taken this issue yet?

**Comment by sighingnow** [comment]
> Has anyone taken this issue yet?

So far no candidate has got in touch.

**Comment by liusitan** [comment]
> 
great! I am excited about this! I wanna try, thanks for the timely response!

**Comment by sighingnow** [comment]
> > 
> 
> great! I am excited about this! I wanna try, thanks for the timely response!

Thanks for being interested in this topic. I will comment more detailed expected design here later.

**Comment by liusitan** [comment]
look forward to that

Best,
Sitan Liu


________________________________

**Comment by sighingnow** [comment]
The basic idea about this proposal can be illustrated using the following example: consider the `.npy` format for numpy ndarray's serialization,

- https://numpy.org/doc/stable/reference/generated/numpy.save.html
- https://numpy.org/doc/stable/reference/generated/numpy.load.html

The `.npy` file is basically a binary dump for a numpy ndarray. It is a binary file that can be stored on disk, with some header bytes, and the payload follows, e.g.,

```
|-- desc --|-- order --|-- shape --|----------  data ---------|
```

Note that the `np.load()` has an option `mmap_mode` to allow the file been memory-mapped as a ndarray, without copying the content into the memory.

Now considering the reverse order, we have a numpy ndarray in memory (considering we have a python variable), we could provide a filesytem interface to allow the ndarray been read as a `.npy` file, by implementing a FUSE driver to adding some header bytes in the read handlers.

Considering now we have a C++ program which implements a reader for the `.npy` file and can take a `.npy` file as input for further processing. If we have such a FUSE driver, then we can avoid actually dumpping the ndarray to filesystem and read it again to pass the ndarray between the Python program and C++ program.

**Comment by sighingnow** [comment]
The case above shows how applications can benifit from such a filesytem layer. In vineyard, the case could be more complicate. We have a hierarchical data model in vineyard, e.g.,

- we have `Blob` for a consective bytes
- We abstract the `Tensor` type over blobs, where the tensor consists of a blob (as the data) and a metadata (key-value pairs, describe the descr, shape, order, etc.)
- We further abstract the `DataFrame` over tensors where each column of a dataframe is a tensor.

Upon such a hierarchical data model, we can provide a overlay file system view for objects in vineyard, as

- We have a basic layer that allows reading blobs as a consective bytes without meaningful metadata
- We have overlay layer on top of the blob layer, which, could understand that some blob constructs some tensors, according to the metadata in the vineyard

**Comment by sighingnow** [comment]
Closing as we have land the pull request #889 and #947.
