### ISSUE TITLE
Integration with machine learning frameworks to seamlessly operate with the trained models

### ISSUE THREAD

**Issue by sighingnow** [v6d-io/v6d#772]
Describe your problem
---------------------

Vineyard already has integrated with various machine learning frameworks, including tensorflow, pytorch and mxnet. Vineyard dataframes, tensors and tables can be used as sources for training and inference. However, the models in those frameworks cannot be `.put()` directly into vineyard.

That needs to be improved!

Additional context
------------------

**Comment by Nageshbansal** [comment]
@sighingnow, can i work on this?,

**Comment by sighingnow** [comment]
Closing as addressed by #1659.
