### ISSUE TITLE
A query abou the tasks dependency of storage order

### ISSUE THREAD

**Issue by JasonNing96** [v6d-io/v6d#785]
Hello, 
       I have some query about the tasks dependency of storage order; Like, If I have some much tasks and they are mutually dependent on each other, task2 should wait for the task1. How this work flow working, Whether V6D waits for the  task01 to complete and complete the storage before executing the task02, and whether V6D has related functions to detect whether the data is ready to complete?

**Comment by sighingnow** [comment]
Closing as we already has a ticket in discussion: https://github.com/v6d-io/v6d/discussions/787
