### ISSUE TITLE
Are all hierarchical metadata of vineyard objects shread across the cluster? 

### ISSUE THREAD

**Issue by liusitan** [v6d-io/v6d#824]
Describe your problem
---------------------
In the vineyard document _dive into vineyard section -> Implementation Details_, it says

> As we mentioned before, each object in Vineyard, consists of two parts:
> 
> 1. The data payload is stored in the corresponding vineyard instance locally
> 
> 2. The hierarchical metadata shared across the vineyard cluster

Are all hierarchical metadata shared across the vineyard clusters?

----------------------------------------------------------------------

Answer: 
no, it is not, it is only shared when the client. persist API is called.

**Comment by sighingnow** [comment]
Will be addressed in the up-coming `data-access` documentation section.

**Comment by sighingnow** [comment]
Addressed by https://v6d.io/notes/objects.html#transient-vs-persistent-objects and https://v6d.io/notes/data-accessing.html.
