### ISSUE TITLE
Make `VINEYARD_SERVER` in CMakeLists.txt into a library for  test file to link

### ISSUE THREAD

**Issue by ZjuYTW** [v6d-io/v6d#835]
Describe your problem
---------------------

I am running into a problem that I want to write a unit test for my #815 pr, and I want to just use the server side source files. It seems if we could make most part of the vineyard_server sources as a library, so I can easily just link it to my unit test.

I will give a draft below to describe what I want to do

or maybe there is a better and elegant way to achieve my target 

----------------------------------------------------------------------

If it is a **feature request**, please provides a clear and concise description of what you want to happen:

### What is the problem:
To make a vineyard_server source files into a library.

### The behaviour that you expect to work:
```cmake
# what i expect the cmake file will be
  if(BUILD_VINEYARD_SERVER)
    file(GLOB_RECURSE SERVER_SRC_FILES "src/server/*/*.cc"
                                       "src/common/memory/*.cc"
                                       "src/common/util/*.cc"
    )
    add_library(vineyard_server ${SERVER_SRC_FILES})
    # ... then we do all link and config stuff on vineyard_server
    add_executable(vineyardd "src/server/vineyardd.cc"
    target_link_libraries(vineyardd vineyard_server)
  endif()
  
 # Then in the test scope
  if(${T_NAME} STREQL  "my_test")
      target_link_libraries(${T_NAME} vineyard_server)
  endif()
```

Additional context
------------------

I am not sure if this will be intrusive to other libraries and I saw there is a command `install_vineyard_target(vineyardd)` in https://github.com/v6d-io/v6d/blob/main/CMakeLists.txt#L557, I don't know if it's safe to change it into `install_vineyard_target(vineyard_server)`

**Comment by sighingnow** [comment]
`vineyardd` is by-design to be a standalone executable to reduce the dependency complexity when deliverying to users via pypi or other package manager.

You could have two target, `vineyardd` and `libvineyardd`, and make them share the same subset of object files to avoid double compliation.

You could find a reference implementation from https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/src/CMakeLists.txt (see how `etcd-cpp-api-core-objects`, `etcd-cpp-api-core` and `etcd-cpp-api` are organized).

**Comment by ZjuYTW** [comment]
After disccussion with @septicmk, I decided to write the `full process` test. So just close this issue is ok
