### ISSUE TITLE
Memory allocate failed even size is smaller than memory limit

### ISSUE THREAD

**Issue by ZjuYTW** [v6d-io/v6d#862]
Describe your problem
---------------------

When I am testing my #815 PR with jemalloc I found the program crashes unexpectedly.  
`Unexpected error occurs during message handling: Not enough memory: Failed to allocate memory of size 7864320, total available memory size are 8388608, and 7864320 are already in use`

Following is how to reproduce the error:
1. Set the memory limit in the `runner.py` as 1024 * 1024 * 8
2. run `cmake .. --DWITH_ALLOCATOR=jemalloc` to generate the makefile
3.  revise the `release_test` 's L54 to `std::vector<double> double_array(480 * 2048, -1);`
4. Run the release_test

Obvious we haven't reached memory limitation but in the `BulkAllocator::Memalign` the spilling check doesn't work and then Allocate is called and returned a `nullptr`. ALSO with allocated_ increased (which is definitely bad)

Additional context
------------------

This can be reproduced on master branch.

**Comment by sighingnow** [comment]
I would take a look.

**Comment by sighingnow** [comment]
The issue has been addressed on main.
