### ISSUE TITLE
Refactor the header dependencies to simplify the usages

### ISSUE THREAD

**Issue by sighingnow** [v6d-io/v6d#905]
Describe your problem
---------------------

e.g., we don't require MPI if we only need to read a arrow fragment.

Additional context
------------------

**Comment by sighingnow** [comment]
FYI /cc @siyuan0322

**Comment by siyuan0322** [comment]
And the vineyard-dev pip wheel.

**Comment by sighingnow** [comment]
The issue should have been resolved by a series of already merged pull requests, e.g., https://github.com/v6d-io/v6d/pull/984.
