### ISSUE TITLE
Add host info in `ArrowFragmentGroup`

### ISSUE THREAD

**Issue by zhanglei1949** [v6d-io/v6d#954]
Feature request

## Problem

It may be useful to provide host info in a `ArrowFragmentGroup`, in case we want to know on which host every fragment lies. Currently we can only get instance ids.

## Expected behavior.

For example.  A string which contains hosts and fragment ids can be obtained by calling `fragGroup->GetFragmentHostIds()`. 
i.e. "h1:1234;h2:6789"

**Comment by sighingnow** [comment]
As discussed off the record, we will add a method on arrowfragmentgroup to return a `object id -> instance id` mapping.

**Comment by sighingnow** [comment]
The API already exists, see: https://github.com/v6d-io/v6d/blob/main/modules/graph/fragment/arrow_fragment_group.h#L49-L53
